export interface TagProperties {
  type: 'double' | 'single',
  display: 'inline' | 'block' | 'inline-block' | 'none' | 'list-item' | 'table' | 'table-header-group' | 'table-column-group' | 'table-column' | 'table-row-group' | 'table-row' | 'table-cell';
  limitParents?: string[];
  limitChildren?: string[];
}

export const dtd: { [tagName: string]: TagProperties } = {
  a: {display: 'inline', type: 'double'},
  abbr: {display: 'inline', type: 'double'},
  acronym: {display: 'inline', type: 'double'},
  address: {display: 'block', type: 'double'},
  applet: {display: 'inline', type: 'double'},
  area: {display: 'inline', type: 'single'},
  article: {display: 'block', type: 'double'},
  aside: {display: 'block', type: 'double'},
  audio: {display: 'none', type: 'double'},
  b: {display: 'inline', type: 'double'},
  base: {display: 'inline', type: 'single', limitParents: ['head']},
  basefont: {display: 'inline', type: 'single'},
  bdi: {display: 'inline', type: 'double'},
  bdo: {display: 'inline', type: 'double'},
  big: {display: 'inline', type: 'double'},
  blockquote: {display: 'block', type: 'double'},
  body: {display: 'block', type: 'double', limitParents: ['html']},
  br: {display: 'inline', type: 'single'},
  button: {display: 'inline-block', type: 'double'},
  canvas: {display: 'inline', type: 'single'},
  center: {display: 'block', type: 'double'},
  cite: {display: 'inline', type: 'double'},
  code: {display: 'inline', type: 'double'},
  command: {display: 'inline', type: 'double'},
  datalist: {display: 'none', type: 'double'},
  dd: {display: 'block', type: 'double', limitParents: ['dl']},
  del: {display: 'inline', type: 'double'},
  details: {display: 'block', type: 'single'},
  dfn: {display: 'inline', type: 'double'},
  dialog: {display: 'none', type: 'double'},
  dir: {display: 'block', type: 'double', limitChildren: ['li']},
  div: {display: 'block', type: 'double'},
  dl: {display: 'block', type: 'double', limitChildren: ['dd', 'dt']},
  dt: {display: 'block', type: 'double', limitParents: ['dl']},
  em: {display: 'inline', type: 'double'},
  embed: {display: 'inline', type: 'single'},
  fieldset: {display: 'block', type: 'double'},
  figcaption: {display: 'block', type: 'double', limitParents: ['figure']},
  figure: {display: 'block', type: 'double'},
  font: {display: 'inline', type: 'double'},
  footer: {display: 'block', type: 'double'},
  form: {display: 'block', type: 'double'},
  h1: {display: 'block', type: 'double'},
  h2: {display: 'block', type: 'double'},
  h3: {display: 'block', type: 'double'},
  h4: {display: 'block', type: 'double'},
  h5: {display: 'block', type: 'double'},
  h6: {display: 'block', type: 'double'},
  head: {display: 'none', type: 'double', limitParents: ['html']},
  header: {display: 'block', type: 'double'},
  hr: {display: 'block', type: 'single'},
  html: {display: 'block', type: 'double', limitChildren: ['head', 'body']},
  i: {display: 'inline', type: 'double'},
  iframe: {display: 'inline', type: 'single'},
  img: {display: 'inline', type: 'single'},
  input: {display: 'inline-block', type: 'single'},
  ins: {display: 'inline', type: 'double'},
  kbd: {display: 'inline', type: 'double'},
  keygen: {display: 'inline', type: 'single'},
  label: {display: 'inline', type: 'double'},
  legend: {display: 'block', type: 'double', limitParents: ['fieldset']},
  li: {display: 'list-item', type: 'double', limitParents: ['ul', 'ol']},
  link: {display: 'none', type: 'single'},
  main: {display: 'block', type: 'double'},
  map: {display: 'inline', type: 'double'},
  mark: {display: 'inline', type: 'double'},
  menu: {display: 'block', type: 'double'},
  menuitem: {display: 'inline', type: 'double'},
  meta: {display: 'none', type: 'single'},
  meter: {display: 'inline-block', type: 'single'},
  nav: {display: 'block', type: 'double'},
  noframes: {display: 'none', type: 'double'},
  noscript: {display: 'inline', type: 'double'},
  object: {display: 'inline', type: 'double'},
  ol: {display: 'block', type: 'double', limitChildren: ['li']},
  optgroup: {display: 'block', type: 'single', limitParents: ['select']},
  option: {display: 'block', type: 'double', limitParents: ['select', 'optgroup']},
  output: {display: 'inline', type: 'double'},
  p: {display: 'block', type: 'double'},
  param: {display: 'none', type: 'single'},
  pre: {display: 'block', type: 'double'},
  progress: {display: 'inline-block', type: 'single'},
  q: {display: 'inline', type: 'double'},
  rp: {display: 'none', type: 'double'},
  rt: {display: 'inline', type: 'double'},
  ruby: {display: 'inline', type: 'double'},
  s: {display: 'inline', type: 'double'},
  samp: {display: 'inline', type: 'double'},
  script: {display: 'none', type: 'double'},
  section: {display: 'block', type: 'double'},
  select: {display: 'inline-block', type: 'single', limitChildren: ['option', 'optgroup']},
  small: {display: 'inline', type: 'double'},
  source: {display: 'inline', type: 'single'},
  span: {display: 'inline', type: 'double'},
  strike: {display: 'inline', type: 'double'},
  strong: {display: 'inline', type: 'double'},
  style: {display: 'none', type: 'double'},
  sub: {display: 'inline', type: 'double'},
  summary: {display: 'block', type: 'double'},
  sup: {display: 'inline', type: 'double'},
  table: {display: 'table', type: 'single', limitChildren: ['thead', 'tbody', 'tr', 'col', 'colgroup']},
  textarea: {display: 'inline-block', type: 'single'},
  time: {display: 'inline', type: 'double'},
  title: {display: 'none', type: 'double', limitParents: ['head']},
  track: {display: 'inline', type: 'single', limitParents: ['video']},
  tt: {display: 'inline', type: 'double'},
  u: {display: 'inline', type: 'double'},
  ul: {display: 'block', type: 'double', limitChildren: ['li']},
  var: {display: 'inline', type: 'double'},
  video: {display: 'inline', type: 'single'},
  wbr: {display: 'inline', type: 'single'},
  thead: {display: 'table-header-group', type: 'single', limitParents: ['table'], limitChildren: ['tr']},
  colgroup: {display: 'table-column-group', type: 'single'},
  col: {display: 'table-column', type: 'single'},
  tbody: {display: 'table-row-group', type: 'single', limitParents: ['table'], limitChildren: ['tr']},
  tr: {display: 'table-row', type: 'single', limitParents: ['tbody', 'table', 'thead'], limitChildren: ['td', 'th']},
  th: {display: 'table-cell', type: 'single', limitParents: ['thead', 'tbody']},
  td: {display: 'table-cell', type: 'single', limitParents: ['thead', 'tbody']}
};
